name: Artifact Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Release Apk
      run: ./gradlew assembleRelease

   - name: Build Debug Apk
      run: ./gradlew assembleDebug

    - name: Upload Release Apk
      uses: actions/upload-artifact@v4
      with:
        name: "Release APK"
        retention-days: 90
        path: "app/build/outputs/apk/release/*.apk"

    - name: Upload Debug Apk
      uses: actions/upload-artifact@v4
      with:
        name: "Debug APK"
        retention-days: 90
        path: "app/build/outputs/apk/debug/*.apk"